CREATE TABLE IF NOT EXISTS pmb_applications (
  id INT NOT NULL AUTO_INCREMENT,
  institution VARCHAR(30) NOT NULL,
  institution_name VARCHAR(120) NOT NULL,
  institution_short VARCHAR(40) NOT NULL,
  jalur_id VARCHAR(50) NULL,
  jalur_name VARCHAR(80) NULL,
  jurusan_id VARCHAR(80) NULL,
  jurusan_name VARCHAR(120) NULL,
  registration_number VARCHAR(60) NOT NULL,
  billing_code VARCHAR(60) NOT NULL,
  billing_amount INT NOT NULL DEFAULT 150000,
  status VARCHAR(40) NOT NULL DEFAULT 'menunggu_verifikasi',
  admin_note TEXT NULL,
  full_name VARCHAR(140) NOT NULL,
  nisn VARCHAR(40) NULL,
  gender VARCHAR(30) NULL,
  birth_place VARCHAR(80) NULL,
  birth_date VARCHAR(30) NULL,
  citizenship VARCHAR(30) NULL,
  religion VARCHAR(40) NULL,
  phone VARCHAR(40) NULL,
  email VARCHAR(120) NULL,
  address TEXT NULL,
  rt VARCHAR(10) NULL,
  rw VARCHAR(10) NULL,
  provinsi VARCHAR(120) NULL,
  kota VARCHAR(120) NULL,
  kecamatan VARCHAR(120) NULL,
  kelurahan VARCHAR(120) NULL,
  school_status VARCHAR(40) NULL,
  school_name VARCHAR(140) NULL,
  school_kecamatan VARCHAR(120) NULL,
  graduation_year VARCHAR(20) NULL,
  certificate_number VARCHAR(80) NULL,
  father_name VARCHAR(120) NULL,
  father_education VARCHAR(60) NULL,
  father_occupation VARCHAR(80) NULL,
  mother_name VARCHAR(120) NULL,
  mother_education VARCHAR(60) NULL,
  mother_occupation VARCHAR(80) NULL,
  guardian_name VARCHAR(120) NULL,
  guardian_occupation VARCHAR(80) NULL,
  parent_income VARCHAR(80) NULL,
  doc_photo_url LONGTEXT NULL,
  doc_ijazah_url LONGTEXT NULL,
  doc_ktp_url LONGTEXT NULL,
  doc_kk_url LONGTEXT NULL,
  payment_proof_url LONGTEXT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY pmb_applications_registration_number_key (registration_number),
  KEY pmb_applications_institution_status_idx (institution, status),
  KEY pmb_applications_registration_number_idx (registration_number)
);
